language: ruby

rvm:
  - "2.6.2"

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libicu-dev
  - sudo apt-get install -y cmake
  - gem install bundler

script: bundle exec rspec spec
